### ISSUE TITLE
[feature request] bep-47 (padding files)

### ISSUE THREAD

**Issue by ikatson** [ikatson/rqbit#255]
https://www.bittorrent.org/beps/bep_0047.html

**Comment by kovalensky** [comment]
Padding files are synthetic files filling every piece to the end, so that clients downloading for instance single file won't have to download and store data for other files. You could see this behaviour as .dat (uTorrent), .parts (qBittorrent), .bcp (Bitcomet).. etc files.

They appear in file list and often being wastefully downloaded by clients not supporting BEP-47.

What I meant by mentioning BEP-53, is that some clients choose indices for padding files too, instead of discarding them, since they are service files and don't contain any value. Thus, while designing that feature this should accounted on.

**Comment by ikatson** [comment]
Not to forget: tried doing it here but it got messy pretty quick, and not sure if worth the bother https://github.com/ikatson/rqbit/compare/main...bep-47

**Comment by ikatson** [comment]
looking again at the referenced branch, we should merge at least some of it, even if it bep-47 isn't supported fully

**Comment by ikatson** [comment]
https://github.com/ikatson/rqbit/pull/270 also

**Comment by ikatson** [comment]
Closing now, the only thing remaining is to not request chunks that are from padding files, bat that's not an easy change and not as worth it (will waste a bit of network bandwidth but otherwise not that important)

**Comment by kovalensky** [comment]
Dazzling, as I see huge effort went to this commit 👍🏻
