### ISSUE TITLE
How to Serve a Private File Between Two rqbit Nodes?

### ISSUE THREAD

**Issue by anchalshivank** [ikatson/rqbit#272]
Hello,

I’m trying to set up a test where I can share a private file between two `rqbit` nodes running on different environments: one in a Docker container and another directly on my laptop.

#### My Setup:
1. I have a private file I want to serve from one `rqbit` instance (acting as a seeder).
2. I'm running the seeder node in a Docker container, where I've specified an `OUTPUT_FOLDER` to store the file.
3. The second `rqbit` instance, running directly on my laptop, acts as the leecher and should download this file from the seeder.

#### Questions:
1. **How do I configure `rqbit` to serve a specific file** that’s already present in the `OUTPUT_FOLDER` of the Docker container? Does `rqbit` support direct seeding from existing files, or is there a specific command needed to add the file to the session?
2. **Is there a way to ensure that the two nodes (Docker and local) can discover each other** and establish a connection? Should I use a tracker or DHT for this private test, or is there another configuration recommended for local peer discovery?

#### What I’ve Tried:
- I’ve successfully created a `.torrent` file for the private file and added it to the `rqbit` session. However, the second node (leecher) is not able to initiate the download, possibly due to connection or discovery issues.

Any guidance on how to properly configure `rqbit` to serve this file between these two nodes would be greatly appreciated!

Thank you in advance for your help!

**Comment by ikatson** [comment]
In short, it's totally possible. In fact, this is what is happening in the [e2e](https://github.com/ikatson/rqbit/blob/main/crates/librqbit/src/tests/e2e.rs) test - it sets up 64 servers, and a client and ensures the client can download it.

## How to replicate in LAN without a tracker

### On the server side
1. Set up the server with a well-known port (e.g. ```rqbit --tcp-min-port 1234 server start```).
1. Add the .torrent to the session, ensure the output folder matches.
1. If the previous step was done correctly, the torrent should detect that the files are already there and will start seeding at 100%.
1. Optionally, disable dht (with --disable-dht), so that it doesn't publish your torrent in DHT.

### On the client side
```rqbit download --initial-peers SERVER_IP:1234 <.torrent file or infohash> -o client_output_folder``` or the equivalent through API. Note the "initial-peers" as the discovery mechanism.

Note: I suggest using main branch

## Note on "private" file
If the file is really "private" and should not be exposed to the outside world under any circumstances, care must be taken. You need to:
1. ensure DHT is disabled
1. tcp-listen listens on 0.0.0.0 and there's no option to change it today. So ensure that rqbit is not exposed to WAN. If you use docker, the deault (non-host) network should do the job, but still expose port 1234 (in the example above)
1. disable upnp port forward

## Note on other discovery mechanisms
1. If you use public DHT as the discovery mechanism the server should have a public IP or expose itself via UpnP (and your router should have public IP for that).
4. Otherwise you can set-up a tracker in your LAN, I've never done this, not sure how to do it, but shouldn't be hard I guess.
